DROP TABLE CONGESTION.Empresa_Rubro
DROP TABLE CONGESTION.Factura_Registro
DROP TABLE CONGESTION.Funcionalidad_Rol
DROP TABLE CONGESTION.Rol_Usuario
DROP TABLE CONGESTION.Usuario_Sucursal
DROP TABLE CONGESTION.Rol
DROP TABLE CONGESTION.Funcionalidad
DROP TABLE CONGESTION.Usuario
DROP TABLE CONGESTION.Rubro
DROP TABLE CONGESTION.Item_factura
DROP TABLE CONGESTION.Devolucion
DROP TABLE CONGESTION.Registro
DROP TABLE CONGESTION.Medio_Pago
DROP TABLE CONGESTION.Factura
DROP TABLE CONGESTION.Rendicion
DROP TABLE CONGESTION.Sucursal
DROP TABLE CONGESTION.Empresa
DROP TABLE CONGESTION.Cliente

DROP PROCEDURE CONGESTION.Migrar_Empresas_Rubros
DROP PROCEDURE CONGESTION.Migrar_Facturas
DROP PROCEDURE CONGESTION.Migrar_Pagos
DROP PROCEDURE CONGESTION.Migrar_Rendicion


