DROP TABLE gd_esquema.RegistroFactura
DROP TABLE gd_esquema.Registro
DROP TABLE gd_esquema.FuncionalidadRol
DROP TABLE gd_esquema.UsuarioRol
DROP TABLE gd_esquema.Rol
DROP TABLE gd_esquema.Funcionalidad
DROP TABLE gd_esquema.UsuarioSucursal
DROP TABLE gd_esquema.Usuario
DROP TABLE gd_esquema.ItemFactura
DROP TABLE gd_esquema.Factura
DROP TABLE gd_esquema.Rubro
DROP TABLE gd_esquema.Rendicion
DROP TABLE gd_esquema.Sucursal
DROP TABLE gd_esquema.MedioPago
DROP TABLE gd_esquema.Empresa
DROP TABLE gd_esquema.Cliente
DROP TABLE gd_esquema.Devolucion

DROP PROCEDURE gd_esquema.MigrarSucursal;
DROP PROCEDURE gd_esquema.MigrarClientes;
DROP PROCEDURE gd_esquema.MigrarRubros;